apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-tls-cert
  namespace: nexus
spec:
  commonName: nexus.ne.local
  dnsNames:
  - nexus.ne.local
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: niceneasy-ca
  renewBefore: 360h0m0s
  secretName: nexus-tls
  usages:
  - server auth
  - client auth