apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java:latest
  - image: gcr.io/paketo-buildpacks/nodejs:latest
  - image: gcr.io/paketo-buildpacks/ruby:latest
