apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediaserver-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs4
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /exports/
    server: 192.168.0.39