apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex-tls-cert
  namespace: plex-mediaserver
spec:
  commonName: plex
  dnsNames:
  - plex.ne.local
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: niceneasy-ca
  renewBefore: 360h0m0s
  secretName: plex-tls
  usages:
  - server auth
  - client auth