apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-cert
  namespace: grafana
spec:
  commonName: grafana.ne.local
  dnsNames:
  - grafana.ne.local
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: niceneasy-ca
  renewBefore: 360h0m0s
  secretName: grafana-tls
  usages:
  - server auth
  - client auth