apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vault.niceneasy.ch.0.1.0
spec:
  refName: vault.niceneasy.ch
  version: 0.1.0
  releaseNotes: "first PoC for tanzu packaging, provided as is"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: bluebossa63/vault-tanzu-package@sha256:f3a1cb9f2b29eaf2fba1c2bc40049ea63e69cbfff90d421c0458cbeddbbfebcf
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
      - kapp: {}