apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "bluebossa63/build:1.0-base-cnb"
  runImage:
    image: "bluebossa63/run:1.0-base-cnb"