apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeapps-tls-cert
  namespace: kubeapps
spec:
  commonName: kubeapps
  dnsNames:
  - kubeapps.ne.local
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: niceneasy-ca
  renewBefore: 360h0m0s
  secretName: kubeapps-tls
  usages:
  - server auth
  - client auth