apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls-cert
  namespace: harbor
spec:
  commonName: harbor.ne.local
  dnsNames:
  - harbor.ne.local
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: niceneasy-ca
  renewBefore: 360h0m0s
  secretName: harbor-tls
  usages:
  - server auth
  - client auth