apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jenkins-tls-cert
  namespace: jenkins
spec:
  commonName: jenkins
  dnsNames:
  - jenkins.ne.local
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: niceneasy-ca
  renewBefore: 360h0m0s
  secretName: jenkins-tls
  usages:
  - server auth
  - client auth