apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  labels:
    app: vault
  name: vault-httpproxy
  namespace: vault
spec:
  routes:
  - conditions:
    - prefix: /
    services:
    - name: hashicorp-vault
      port: 8200
  virtualhost:
    fqdn: vault.ne.local
    tls:
      secretName: vault-tls