apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: tph-mgmt-provider
spec:
  provider: vault                             # accepted provider options: azure or vault or gcp
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
    - key: .dockerconfigjson                  # data field to populate
      objectName: secret/registry-secrets    # name of the mounted content to sync. this could be the object name or the object alias
    secretName: registry-credentials          # name of the Kubernetes Secret object
    type: kubernetes.io/dockerconfigjson      # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls
  parameters:
    vaultAddress: "http://vault.hashicorp-vault:8200"
    roleName: "registry-access"
