apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-database
spec:
  provider: vault
  secretObjects:                              # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - secretName: registry-credentials          # name of the Kubernetes Secret object
    type: kubernetes.io/dockerconfigjson      # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls  
    data:
    - objectName: registry-secrets            # name of the mounted content to sync. this could be the object name or the object alias
      key: ".dockerconfigjson"                # data field to populate
  - secretName: test
    type: Opaque
    data:
    - objectName: db-password
      key: key
  parameters:
    vaultAddress: "http://vault.hashicorp-vault:8200"
    roleName: "database"
    objects: |
      - objectName: "db-password"
        secretPath: "secret/data/db-pass"
        secretKey: "password"
      - objectName: "registry-secrets"
        secretPath: "secret/data/registry-secrets"
        secretKey: ".dockerconfigjson"