apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls-cert
  namespace: hashicorp-vault
spec:
  commonName: vault.ne.local
  dnsNames:
  - vault.ne.local
  duration: 87600h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: niceneasy-ca
  renewBefore: 360h0m0s
  secretName: vault-tls
  usages:
  - server auth
  - client auth