apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: builder
  namespace: default
spec:
  serviceAccountName: kpack-service-account
  tag: harbor.ne.local/tph-local/builder:1.2.0
  stack:
    name: full
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id: paketo-buildpacks/nodejs
