apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: supply-chain-k8s
spec:
  serviceAccountRef:
    name: workload-user-sa
  selector:
    apps.tanzu.vmware.com/workload-type: web-k8s
  resources:
  - name: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: source
  - name: image-builder
    templateRef:
      kind: ClusterImageTemplate
      name: image
    params:
    - name: image_prefix
      value: harbor.ne.local/tph-local/
    sources:
    - resource: source-provider
      name: source
  - name: deployer
    templateRef:
      kind: ClusterTemplate
      name: app-deploy-k8s
    images:
    - resource: image-builder
      name: image
