
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/bluebossa63/tanzu-simple-web-app
      ref:
        branch: main
