namespace: metallb-system

resources:
  - github.com/metallb/metallb//manifests?ref=v0.11.0
  - ./metallb-cm.yml
  - ./clusterrole.yml
  - ./clusterrolebinding.yml
#  - ./metallb-scc.yml

# patchesStrategicMerge:
#   - |-
#     apiVersion: apps/v1
#     kind: Deployment
#     metadata:
#       name: controller
#       namespace: metallb-system
#     spec:
#       template:
#         spec:
#           securityContext:
#             $patch: replace
#             runAsNonRoot: true
